install.packages("tidymodels")
install.packages("tidyverse")
install.packages("skimr")
install.packages("infer")
install.packages("corr")
install.packages("spatialsample")
install.packages("baguette")
install.packages("workflowsets")
install.packages("finetune")
install.packages("usemodels")
install.packages("probably")
install.packages("shinymodels")
install.packages("hardhat")

install.packages("splines")
install.packages("doParallel")

install.packages("cansim")
install.packages("writexl")
install.packages("lubridate")
install.packages("zoo")
install.packages("fredr")
install.packages("readxl")
install.packages("httr")
install.packages("jsonlite")
install.packages("data.table")
install.packages("seasonal")
install.packages("seasonalview")
